import { Size, Colour, Brand, Category } from "./";
import { Gender } from "./gender";
import { ProductQuantity } from "./product.quantity";
export class Product {
  $key?: string;
  productId?: string;
  productName?: string;
  productCategoryId?: number;
  productCategory?: string;
  productCategoryVM?: Category;
  productDescription?: string;
  genderKey?: string;
  gender?: string;
  genderVM?: Gender;
  productPrice?: number;
  productImageUrl?: string;
  productAdded?: number;
  ratings?: number;
  favourite?: boolean;
  productSeller?: string;
  material?: string;
  materialComposition?: string;
  liningMaterial?: string;
  colour?: Colour[];
  sizeType?: number;
  size?: Size;
  modelDetails?: string;
  isProductAvailable?: boolean;
  productBrandName?: string;
  productBrand?: Brand;
  productQuantity?: ProductQuantity[];
}
